### ISSUE TITLE
Plugin won't load and seemingly won't update

### ISSUE THREAD

**Issue by moeraccoon** [belzaru17/WorkshopOptimizerPlugin#11]
I'm sure it's my fault somehow, or I'm missing something obvious, but it's not working for me anymore so I was wondering if there's anything I can do to get it running once again.
When I saw it didn't load I restarted the game. Still didn't load. So I uninstalled it and tried to reinstall it. 
It's possibly worth pointing out that I'm on linux.

I hope formatting for the log isn't terrible.
`09:46:43.002 | INF [Penumbra] 0 Individual Assignments loaded after delay.
09:46:43.560 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis18, 18pt, skew=0, weight=0)" has been requested.
09:46:43.617 | INF [Penumbra] Penumbra Version 0.7.2.2, Commit #c3b106e successfully Loaded from https://raw.githubusercontent.com/Ottermandias/SeaOfStars/main/repo.json.
09:46:43.618 | INF [Penumbra] Loading native OtterTex assembly from Z:\home\raccoon\.xlcore\installedPlugins\Penumbra\0.7.2.2.
09:46:43.618 | INF [LOCALPLUGIN] Finished loading Penumbra.dll
09:46:43.619 | INF [PLUGINM] ============= LoadPluginsSync(AnytimeSync) END =============
09:46:43.619 | INF [PLUGINM] ============= LoadPluginsAsync(AnytimeAsync) START =============
09:46:43.621 | INF [PLUGINM] ============= LoadPluginsAsync(AnytimeAsync) END =============
09:46:43.621 | INF [SPL] [T3] PML OK!
09:46:43.823 | INF [IME] Enabled!
09:46:44.126 | INF [PLUGINM] ============= LoadPluginsSync(FrameworkTickSync) START =============
09:46:44.127 | INF [PLUGINM] ============= LoadPluginsSync(FrameworkTickSync) END =============
09:46:44.127 | INF [PLUGINM] ============= LoadPluginsAsync(FrameworkTickAsync) START =============
09:46:44.128 | INF [PLUGINM] ============= LoadPluginsAsync(FrameworkTickAsync) END =============
09:46:44.523 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) START =============
09:46:44.524 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) END =============
09:46:44.524 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) START =============
09:46:44.526 | INF [PLUGINM] Loading plugin Glamourer
09:46:44.526 | INF [PLUGINM] Loading plugin Heliosphere
09:46:44.526 | INF [PLUGINM] Loading plugin Honorific
09:46:44.526 | INF [PLUGINM] Loading plugin Hunt Helper
09:46:44.526 | INF [PLUGINM] Loading plugin MakePlace Plugin
09:46:44.526 | INF [PLUGINM] Loading plugin Mare Synchronos
09:46:44.526 | INF [PLUGINM] Loading plugin ezMiniCactpot
09:46:44.526 | INF [PLUGINM] Loading plugin No Tank You
09:46:44.526 | INF [PLUGINM] Loading plugin Palette+
09:46:44.526 | INF [PLUGINM] Loading plugin Simple Heels
09:46:44.537 | INF [LOCALPLUGIN] Loading MiniCactpotSolver.dll
09:46:44.537 | INF [LOCALPLUGIN] Loading Honorific.dll
09:46:44.539 | INF [LOCALPLUGIN] Loading SimpleHeels.dll
09:46:44.539 | INF [LOCALPLUGIN] Loading PalettePlus.dll
09:46:44.547 | INF [LOCALPLUGIN] Loading MakePlacePlugin.dll
09:46:44.549 | INF [LOCALPLUGIN] Loading HuntHelper.dll
09:46:44.550 | INF [LOCALPLUGIN] Loading NoTankYou.dll
09:46:44.550 | INF [LOCALPLUGIN] Loading Glamourer.dll
09:46:44.551 | INF [LOCALPLUGIN] Loading CustomizePlus.dll
09:46:44.578 | INF [LOCALPLUGIN] Finished loading MiniCactpotSolver.dll
09:46:44.578 | INF [PLUGINM] Loading plugin ReSanctuary
09:46:44.582 | INF [LOCALPLUGIN] Loading ReSanctuary.dll
09:46:44.588 | INF [LOCALPLUGIN] Loading heliosphere-plugin.dll
09:46:44.592 | INF [HuntHelper] Loaded language file: Z:\home\raccoon\.xlcore\installedPlugins\HuntHelper\1.0.0.7\Data\Localisation\english.json
09:46:44.599 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis36, 42pt, skew=0, weight=0)" has been requested.
09:46:44.608 | INF [LOCALPLUGIN] Loading MareSynchronos.dll
09:46:44.611 | ERR [CustomizePlus] Unable to load plugin config
System.IO.FileNotFoundException: Specified config path is invalid
   at CustomizePlus.Data.Configuration.ConfigurationManager.LoadConfigurationFromFile(String path) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Data\Configuration\ConfigurationManager.cs:line 58
   at CustomizePlus.Data.Configuration.ConfigurationManager.ReloadConfiguration() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Data\Configuration\ConfigurationManager.cs:line 44
09:46:44.673 | INF [CustomizePlus] Loading and converting legacy profiles...
09:46:44.676 | INF [CustomizePlus] Legacy load complete
09:46:44.683 | INF [CustomizePlus] Loading profiles from directory...
09:46:44.689 | INF [CustomizePlus] Directory load complete
09:46:44.784 | INF [LOCALPLUGIN] Finished loading CustomizePlus.dll
09:46:44.837 | INF [MakePlacePlugin] Hooking IsSaveLayoutDetour at 1405CAE60
09:46:44.941 | INF [MakePlacePlugin] Hooking SelectItemDetour at 1405C4AC0
09:46:44.951 | INF [MakePlacePlugin] Hooking UpdateYardObj at 140B12F60
09:46:44.964 | INF [LOCALPLUGIN] Finished loading Honorific.dll
09:46:44.966 | INF [MakePlacePlugin] Hooking GetGameObject at 140B15300
09:46:45.156 | INF [LOCALPLUGIN] Finished loading ReSanctuary.dll
09:46:45.186 | INF [MakePlacePlugin] Hooking GetObjectFromIndex at 14143B0C0
09:46:45.240 | INF [MakePlacePlugin] Hooking GetYardIndex at 140B0FBB0
09:46:45.244 | INF [LOCALPLUGIN] Finished loading PalettePlus.dll
09:46:45.272 | INF [LOCALPLUGIN] Finished loading SimpleHeels.dll
09:46:45.280 | INF [LOCALPLUGIN] Finished loading NoTankYou.dll
09:46:45.499 | INF [MakePlacePlugin] Loaded 4 landset rows
09:46:45.499 | INF [MakePlacePlugin] Loaded 1355 furniture
09:46:45.499 | INF [MakePlacePlugin] Loaded 308 yard objects
09:46:45.500 | INF [MakePlacePlugin] Loaded 208 united parts
09:46:45.500 | INF [MakePlacePlugin] Loaded 121 dyes
09:46:45.500 | INF [MakePlacePlugin] Loaded 431 items with AdditionalData
09:46:45.502 | INF [MakePlacePlugin] MakePlace Plugin v2.25 initialized
09:46:45.502 | INF [LOCALPLUGIN] Finished loading MakePlacePlugin.dll
09:46:45.515 | INF [LOCALPLUGIN] Finished loading HuntHelper.dll
09:46:45.765 | INF [LOCALPLUGIN] Finished loading heliosphere-plugin.dll
09:46:46.005 | INF [MareSynchronos] [     MarePlugin]{2} Launching Mare Synchronos 0.8.50
09:46:46.007 | INF [MareSynchronos] [       Lifetime]{2} Application started. Press Ctrl+C to shut down.
09:46:46.007 | INF [MareSynchronos] [       Lifetime]{2} Hosting environment: Production
09:46:46.007 | INF [MareSynchronos] [       Lifetime]{2} Content root path: Z:\home\raccoon\.xlcore\pluginConfigs\MareSynchronos
09:46:46.014 | INF [LOCALPLUGIN] Finished loading MareSynchronos.dll
09:46:46.381 | INF [Penumbra] WebServer New State - Loading
09:46:46.402 | INF [Penumbra] WebServer New State - Listening
09:46:46.420 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Jupiter23, 23pt, skew=0, weight=0)" has been requested.
09:46:46.434 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Jupiter23, 23pt, skew=0, weight=0)" has been requested.
09:46:46.481 | INF [Penumbra] Registered /penumbra with Dalamud.
09:46:54.163 | ERR [Penumbra.GameData] Error creating shared actor data for WeaponIdentification:
Dalamud.Plugin.Ipc.Exceptions.DataCacheTypeMismatchError: Data cache Penumbra.GameData.WeaponIdentification.English.V1 was requested with type System.Collections.Generic.List`1[System.ValueTuple`2[System.UInt64,Penumbra.GameData.Structs.EquipItem]], but Penumbra created type System.Collections.Generic.List`1[System.ValueTuple`2[System.UInt64,System.ValueTuple`7[System.String,System.UInt64,System.UInt16,System.UInt16,System.UInt16,System.Byte,System.Byte]]].
   at Dalamud.Plugin.Ipc.Internal.DataShare.GetOrCreateData[T](String tag, Func`1 dataGenerator) in C:\goatsoft\companysecrets\dalamud\Plugin\Ipc\Internal\DataShare.cs:line 48
   at Dalamud.Plugin.DalamudPluginInterface.GetOrCreateData[T](String tag, Func`1 dataGenerator) in C:\goatsoft\companysecrets\dalamud\Plugin\DalamudPluginInterface.cs:line 248
   at Penumbra.GameData.Data.DataSharer.TryCatchData[T](DalamudPluginInterface pi, String tag, ClientLanguage language, Int32 version, Func`1 func)
09:47:01.377 | INF [LOCALPLUGIN] Finished loading Glamourer.dll
09:47:01.378 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) END =============
09:47:01.378 | INF [PLUGINM] Loaded plugins on boot
09:47:01.391 | INF Saved cache to "Z:\home\raccoon\.xlcore\dalamud\Hooks\7.9.0.0\cachedSigs\2023.07.06.0000.0000.json"
09:47:16.555 | INF [PLUGINM] Starting plugin update
09:47:16.558 | INF [PLUGINM] Plugin update OK.
09:47:16.848 | WRN [HITCH] Long "FrameworkUpdate" detected, 109.722ms > 50ms - check in the plugin stats window.
09:47:21.202 | WRN [HITCH] Long "GameNetworkDown" detected, 39.7645ms > 30ms - check in the plugin stats window.
09:47:26.331 | INF [MareSynchronos] [  ApiController]{2} Recreating Connection
09:47:27.648 | INF [MareSynchronos] [WebSoc...nsport]{2} Starting transport. Transfer mode: Binary. Url: 'wss://maresynchronos.com/mare?id=QnYPSKJwSqgZZGd_vf4z8g'.
09:47:27.673 | ERR [MareSynchronos] [ HttpConnection]{4} Failed to start connection. Error starting transport 'WebSockets'.: Unable to connect to the remote server
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
09:47:27.720 | INF [MareSynchronos] [LongPo...nsport]{2} Starting transport. Transfer mode: Binary.
09:47:27.777 | INF [MareSynchronos] [ HttpConnection]{2} HttpConnection Started.
09:47:27.790 | INF [MareSynchronos] [  HubConnection]{2} Using HubProtocol 'messagepack v1'.
09:47:27.883 | INF [MareSynchronos] [  HubConnection]{2} HubConnection started.
09:47:27.948 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 288.9225ms
09:47:28.433 | INF [MareSynchronos] [Player...actory]{2} Building character data for MinionOrMount took 245.1571ms
09:47:28.593 | INF [MareSynchronos] [Notifi...ervice]{2} NotificationMessage { KeepThreadContext = False, Title = Info from Lunae Crescere Incipientis (Central Server EU), Message = Welcome to Mare Synchronos "Main", Current Online Users: 11009, Type = Info, TimeShownOnScreen = 5000 }
09:47:41.701 | INF [PLUGINM] Now reloading all PluginMasters...
09:47:41.701 | INF [PLUGINR] Fetching repo: https://kamori.goats.dev/Plugin/PluginMaster
09:47:41.929 | INF [PLUGINR] Successfully fetched repo: https://kamori.goats.dev/Plugin/PluginMaster
09:47:41.929 | INF [PLUGINR] Fetching repo: https://raw.githubusercontent.com/jawslouis/MakePlacePlugin/master/MakePlacePlugin.json
09:47:41.929 | INF [PLUGINR] Fetching repo: https://raw.githubusercontent.com/Ottermandias/SeaOfStars/main/repo.json
09:47:41.938 | INF [PLUGINR] Successfully fetched repo: https://raw.githubusercontent.com/jawslouis/MakePlacePlugin/master/MakePlacePlugin.json
09:47:41.939 | INF [PLUGINR] Successfully fetched repo: https://raw.githubusercontent.com/Ottermandias/SeaOfStars/main/repo.json
09:47:41.939 | INF [PLUGINM] PluginMasters reloaded, now refiltering...
09:47:47.781 | ERR Plugin image1 for WorkshopOptimizerPlugin at queue was larger than the maximum allowed resolution (1232x700 > 730x380).
09:47:47.812 | ERR Plugin image4 for WorkshopOptimizerPlugin at queue was larger than the maximum allowed resolution (1231x700 > 730x380).
09:47:47.880 | ERR Plugin image3 for WorkshopOptimizerPlugin at queue was larger than the maximum allowed resolution (1230x699 > 730x380).
09:47:48.349 | ERR Plugin image2 for WorkshopOptimizerPlugin at queue was larger than the maximum allowed resolution (1231x701 > 730x380).
09:47:50.615 | INF [PLUGINM] Installed plugin Workshop Optimizer Plugin (testing=False)
09:47:50.615 | INF [PLUGINM] Loading plugin Workshop Optimizer Plugin
09:47:50.621 | INF [LOCALPLUGIN] Loading WorkshopOptimizerPlugin.dll
09:47:50.646 | ERR [LOCALPLUGIN] Error while loading Workshop Optimizer Plugin
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at WorkshopOptimizerPlugin.Data.SeasonUtils.SeasonStart()
   at WorkshopOptimizerPlugin.Persistence.Internal.PersistentSeasonData..ctor()
   at WorkshopOptimizerPlugin.Persistence.Internal.PersistentData..ctor(Configuration configuration)
   at WorkshopOptimizerPlugin.Persistence.DataSource..ctor(Configuration configuration)
   at WorkshopOptimizerPlugin.Persistence.DataSource.Load(Configuration configuration, String filename)
   at WorkshopOptimizerPlugin.Windows.Utils.UIDataSource.Load(Configuration configuration)
   at WorkshopOptimizerPlugin.Windows.MainWindow..ctor(Plugin plugin)
   at WorkshopOptimizerPlugin.Plugin..ctor(DalamudPluginInterface pluginInterface, CommandManager commandManager, ChatGui chatGui)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 134
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 490
09:47:50.650 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at WorkshopOptimizerPlugin.Data.SeasonUtils.SeasonStart()
   at WorkshopOptimizerPlugin.Persistence.Internal.PersistentSeasonData..ctor()
   at WorkshopOptimizerPlugin.Persistence.Internal.PersistentData..ctor(Configuration configuration)
   at WorkshopOptimizerPlugin.Persistence.DataSource..ctor(Configuration configuration)
   at WorkshopOptimizerPlugin.Persistence.DataSource.Load(Configuration configuration, String filename)
   at WorkshopOptimizerPlugin.Windows.Utils.UIDataSource.Load(Configuration configuration)
   at WorkshopOptimizerPlugin.Windows.MainWindow..ctor(Plugin plugin)
   at WorkshopOptimizerPlugin.Plugin..ctor(DalamudPluginInterface pluginInterface, CommandManager commandManager, ChatGui chatGui)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 134
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 490
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1366
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 882
09:49:14.612 | INF [PLUGINM] Installed plugin AutoMammet (testing=False)
09:49:14.612 | INF [PLUGINM] Loading plugin AutoMammet
09:49:14.615 | WRN [PROFMAN] "AutoMammet" was not in any profile, adding to default with True
09:49:14.617 | INF [LOCALPLUGIN] Loading AutoMammet.dll
09:49:14.634 | INF [LOCALPLUGIN] Finished loading AutoMammet.dll
{ } [ Send ]
`

**Comment by belzaru17** [comment]
Thanks for the report (and log!). 0.2.7.3 should fix it (should be up once approved).
